# Generated by Django 4.2.5 on 2024-02-04 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 17, 37, 42, 902235, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
