# Generated by Django 4.2.5 on 2024-02-08 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_delivery_date_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 10, 1, 25, 558738, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
